name: Main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Typecheck
      run: npm run build

    - name: Check formatting
      run: npm run prettier:check 

    - name: Test
      run: npm test 

